version: "3"

services:
  sybim_gui:
    build: gui
    ports:
      - ${SYBIM_GUI_PORT}:80

    environment:
      - SYNC_SERVER_HOST=sybim_server
      - SYNC_SERVER_PORT=1331

  sybim_server:
    build: server
    ports:
      - ${SYBIM_SERVER_PORT}:1331
